# Generated by Django 5.1.3 on 2024-11-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=50)),
                ('mode', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], max_length=50)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
