# Generated by Django 5.1.3 on 2024-11-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_invitee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
    ]
