# Generated by Django 5.1.3 on 2024-11-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
